---
title: "exploring-dives"
format: 
  html: 
    toc: true
    html-math-method: mathjax
vignette: >
  %\VignetteIndexEntry{Exploring Dives}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
bibliography: references.bib
---

## Summary

### Goal

Create a tool for classifying seal dive types. I believe the relevant references are @robinson2010 and @boeuf1988.

### Approach

Use **active learning** to build a labeled dataset *and* train the model simultaneously. Active learning serves unlabeled examples (in this case, dives) to the expert user (e.g., a marine mammalogist) for classification. This is faster than strictly supervised learning, which requires the user to create the labeled dataset *in advance*. It still has the advantages of using a machine learning algorithm suitable for the task. Here, we'll treat the classification task as a *time series classification* problem and, given the simplicity of the data, use a readily-interpretable algorithm called *Time Series Forest* [@deng2013].

### Data

A large amount of northern elephant seal (*Mirounga angustirostris*) was published in *Scientific Data* in 2024 [@costa2024], which we'll use here. The level 1 and 2 (ungridded) data were deposited in Dryad [@costa2024a]. I downloaded the 2017 "raw curated" data and placed them in `data-raw/`. They are too large for GitHub (\~650MB), so anyone following along should download the same file (2017_RawCurated.zip) manually.

## Visualize a sample

```{r}
#| label: setup

library(dplyr)
library(ggplot2)
theme_set(theme_bw())

```
